### ISSUE TITLE
nouns should be plural

### ISSUE THREAD

**Issue by konsumer** [backstopmedia/gRPC-book-example#5]
We should use a single noun-name (plural form) for http annotations.

now:

`/people` and `/person/{ID}`

should be:

`/people/` and `/people/{ID}`

**Comment by konsumer** [comment]
My original thought with this is that it's still only RESTish, and in that case I should make the http annotations match the gRPC names of plural vs singular a bit more. I can see how it might be a bit confusing, though.

**Comment by pseudomuto** [comment]
I think this was resolved in #2
